FROM s390x/node:6.9.0

RUN apt update && apt install -y git 
RUN git clone https://github.com/ibm-blockchain/marbles && cd marbles && npm install && npm install -g gulp

WORKDIR marbles

COPY blockchain_creds1.json config/blockchain_creds1.json
COPY marbles1.json config/marbles1.json
COPY start.sh /usr/bin/start.sh
RUN chmod +x /usr/bin/start.sh

CMD ["start.sh"]
