version: '2'

networks:
  blockchain.com:

services:
  fabric-peer:
    image: dhyeyibm/fabric-peer:local
    restart: unless-stopped
    hostname: fabric-peer
    ports:
      - 5011:5011
      - 5010:5010
    environment: 
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_NETWORKID=connectacloud
      - CORE_PEER_ADDRESS=fabric-peer.net_blockchain.com:5011
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5011
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:5010
      #- CORE_PEER_GOSSIP_BOOTSTRAP=fabric-peer:5011
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_LOCALMSPID=${PEERMSPID}
      - CORE_PEER_MSPCONFIGPATH=/mnt/msp
      - CORE_LOGGING_LEVEL=info
      - CORE_PEER_ID=fabric-peer
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/certs/peerlocal-cert.pem
      - CORE_PEER_TLS_KEY_FILE=/certs/peerlocal-key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/certs/cacert.pem
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=fabric-peer.net_blockchain.com
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=net_blockchain.com
      - PEER_CFG_PATH=/mnt
      - CA_URL=${CA_URL}
      - CA_USER=${CA_USER}
      - CA_PASSWORD=${CA_PASSWORD}
      - TLS_HSBN_CERT=${TLS_HSBN_CERT}
      - ORDERER_URL=${ORDERER_URL}
      - CHANNEL_NAME=${CHANNEL_NAME}
    volumes:
      - ./config:/mnt/
      - ./tls:/certs
      - /var/run:/host/var/run/
    networks:
      - blockchain.com