version: '2'

services:
  fabric-peer-local:
    image: dhyeyibm/fabric-peer:local
    restart: unless-stopped
    hostname: fabric-peer-local
    ports:
      - 5011:5011
      - 5010:5010
    environment: 
      - CORE_PEER_ADDRESSAUTODETECT=false
      - CORE_PEER_NETWORKID=connectacloud
      - CORE_PEER_ADDRESS=localhost:5011
      - CORE_PEER_LISTENADDRESS=0.0.0.0:5011
      - CORE_PEER_EVENTS_ADDRESS=0.0.0.0:5010
      - CORE_PEER_GOSSIP_BOOTSTRAP=localhost:5011
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_GOSSIP_SKIPHANDSHAKE=true
      - CORE_PEER_COMMITTER_ENABLED=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_DISCOVERY_PERIOD=60s
      - CORE_PEER_DISCOVERY_TOUCHPERIOD=60s
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_LOCALMSPID=PeerOrg1
      - CORE_PEER_MSPCONFIGPATH=/mnt/msp
      - CORE_LOGGING_LEVEL=debug
      - CORE_PEER_ID=fabric-peer-local
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/certs/peerlocal-cert.pem
      - CORE_PEER_TLS_KEY_FILE=/certs/peerlocal-key.pem
      - CORE_PEER_TLS_ROOTCERT_FILE=/certs/cacert.pem
      - CORE_PEER_TLS_SERVERHOSTOVERRIDE=localhost
      - PEER_CFG_PATH=/mnt
      - CA_HOST=tor-zbc02a.3.secure.blockchain.ibm.com
      - CA_PORT=11311
      - CA_USER=admin
      - CA_PASSWORD=12387b87ea
      - TLS_HSBN_CERT=/certs/3.secure.cert
      - ORDERER_URL=tor-zbc02a.3.secure.blockchain.ibm.com:11305
      - CHANNEL_NAME=mychannel
    volumes:
      - ./config:/mnt/
      - ./tls:/certs
      - /var/run:/host/var/run/